### ISSUE TITLE
Doesnt work in IE 11

### ISSUE THREAD

**Issue by marklnichols** [ndmitchell/debug#27]
Not sure about any other versions, but the functions, variables, and code are all missing in IE 11.

**Comment by pepeiborra** [comment]
This should be addressed by https://github.com/ndmitchell/debug/pull/30

**Comment by ndmitchell** [comment]
Thanks merged, @marklnichols - can you confirm?

**Comment by marklnichols** [comment]
It still doesn't seem to work:

![image](https://user-images.githubusercontent.com/16517726/35370062-7a5dc0a0-0159-11e8-93c6-a75f1ffa4156.png)

**Comment by ndmitchell** [comment]
I fixed some Javascript - Mark, please confirm now.

**Comment by marklnichols** [comment]
Looks good now =)
